### ISSUE TITLE
Create Comparison LWC component

### ISSUE THREAD

**Issue by kryvyifedir** [kryvyifedir/game-force#10]
Add an ability for user to click on the card of the user to compare his and user achievements
<img width="1074" alt="image" src="https://github.com/kryvyifedir/game-force/assets/23722132/50f3f7cd-341d-40d2-86ab-5c7672020046">

UI should be done as modal window that displays information about current user and user that he has clicked on and lists with their achievements:

[--------------------------------------]
[ Curent User Card | Clicked User Card ]  -> (nor scrollable and is always on screen)
[--------------------------------------]
[ Achievement 1      | Achievement 1      ] -> (both lists are scrolled together. 
[ Achievement 2     | Achievement 2      ]       lists are orderd by achievement name, 
[ Achievement 3      | Achievement 3     ]      lists show both reached and unreached achievements)

**Comment by kryvyifedir** [comment]
@Andr11Kuzmenko are you working on this one already? I see that you have moved it to in-progress but haven't assigned to yourself or created a branch for it

**Comment by Andr11Kuzmenko** [comment]
@kryvyifedir  assigned.

**Comment by kryvyifedir** [comment]
@Andr11Kuzmenko are you actively working on it? Because I haven't seen any branch created

**Comment by Andr11Kuzmenko** [comment]
@kryvyifedir  will create a PR today
